time_step_seconds: 0.03
log_every_frames: 10
environment: cruise_ship
sources:
- '82'
- '83'
- '73'
- '77'
- '92'
agents:
- 5
- 5
- 6
- 6
- 10
targets:
- '163'
- '164'
mode_type: 0
risk_seed: 233
risk_iterations: 7000
risk_increase_chance: 0.05
starting_risks:
- - '8'
  - 1.0
risk_overrides:
- - 2200
  - '153'
  - 0.6
- - 2200
  - '225'
  - 1.0
- - 2200
  - '224'
  - 1.0
- - 2200
  - '201'
  - 0.6
risk_threshold: 0.5
propagation_threshold: 0.5
gamma: 0.3
stairs_max_speed: 0.6
normal_max_speed: 1.2
every_nth_frame_simulation: 3
every_nth_frame_animation: 50
