example_case:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 233
  risk_iterations: 7000
  risk_increase_chance: 0.005 #0.05
  starting_risks:
    - ["8", 1.0]
  risk_overrides:
    - [2350, "153", 0.6]
    - [2350, "225", 1.0]
    - [2350, "224", 1.0]
    - [2350, "201", 0.6]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 2500

representative_case:
  environment: "cruise_ship"
  sources: ["82", "83", "73", "77", "92"]
  agents: [5, 5, 6, 6, 10]
  targets: ["163", "164"]
  mode_type: 0
  master_seed: 233
  risk_iterations: 7000
  risk_increase_chance: 0.001
  starting_risks:
    - ["8", 1.0]
  risk_overrides:
    - [2200, "153", 0.6]
    - [2200, "225", 1.0]
    - [2200, "224", 1.0]
    - [2200, "201", 0.6]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.3
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 2200

representative_case_theme_park:
  environment: "theme_park"
  sources: [ "1", "4", "35", "50" ]
  agents: [ 13, 7, 6, 4 ]
  targets: [ "65", "23" ]
  mode_type: 0
  master_seed: 2468
  risk_iterations: 7000
  risk_increase_chance: 0.0001
  starting_risks:
    - [ "67", 1.0 ]
    - [ "54", 1.0 ]
    - [ "28", 1.0 ]
    - [ "17", 1.0 ]
    - [ "11", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 2200

######## CORRIDOR CASES ############

corridor_case_1:
  environment: "corridor"
  sources: ["16"]
  agents: [5]
  targets: ["1", "14"]
  mode_type: 0
  master_seed: 1001
  risk_iterations: 2000
  risk_increase_chance: 0.05
  starting_risks:
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500

corridor_case_2:
  environment: "corridor"
  sources: ["16"]
  agents: [10]
  targets: ["1"]
  mode_type: 0
  master_seed: 1002
  risk_iterations: 2000
  risk_increase_chance: 0.05
  starting_risks:
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500

corridor_case_3:
  environment: "corridor"
  sources: ["16"]
  agents: [20]
  targets: ["1"]
  mode_type: 0
  master_seed: 1003
  risk_iterations: 2500
  risk_increase_chance: 0.06
  starting_risks:
    - ["9", 1.0]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500

corridor_case_4:
  environment: "corridor"
  sources: ["16"]
  agents: [30]
  targets: ["1", "14"]
  mode_type: 0
  master_seed: 1004
  risk_iterations: 3000
  risk_increase_chance: 0.05
  starting_risks:
    - ["11", 1.0]
    - ["12", 0.7]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500

corridor_case_5:
  environment: "corridor"
  sources: ["9"]
  agents: [15]
  targets: ["14"]
  mode_type: 0
  master_seed: 1005
  risk_iterations: 2000
  risk_increase_chance: 0.04
  starting_risks:
    - ["4", 0.9]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500

corridor_case_6:
  environment: "corridor"
  sources: ["9"]
  agents: [25]
  targets: ["1"]
  mode_type: 0
  master_seed: 1006
  risk_iterations: 2500
  risk_increase_chance: 0.06
  starting_risks:
    - ["10", 1.0]
    - ["11", 1.0]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500

corridor_case_7:
  environment: "corridor"
  sources: ["16", "9", "5"]
  agents: [10, 10, 10]
  targets: ["1", "14"]
  mode_type: 0
  master_seed: 1007
  risk_iterations: 3000
  risk_increase_chance: 0.05
  starting_risks:
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500


corridor_case_8:
  environment: "corridor"
  sources: ["16"]
  agents: [40]
  targets: ["14", "1"]
  mode_type: 0
  master_seed: 1008
  risk_iterations: 3500
  risk_increase_chance: 0.07
  starting_risks:
    - ["11", 1.0]
    - ["12", 1.0]
    - ["13", 0.8]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500


corridor_case_9:
  environment: "corridor"
  sources: ["9"]
  agents: [50]
  targets: ["1"]
  mode_type: 0
  master_seed: 1009
  risk_iterations: 4000
  risk_increase_chance: 0.08
  starting_risks:
    - ["10", 1.0]
    - ["11", 1.0]
    - ["12", 1.0]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500


corridor_case_10:
  environment: "corridor"
  sources: ["16", "9"]
  agents: [20, 20]
  targets: ["1", "14"]
  mode_type: 0
  master_seed: 1010
  risk_iterations: 5000
  risk_increase_chance: 0.1
  starting_risks:
    - ["10", 1.0]
    - ["11", 1.0]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 500


####################################

######## CRUISE SHIP CASES ########

cruise_ship_case_1:
  environment: "cruise_ship"
  sources: ["92", "70", "61", "119", "85"]
  agents: [5, 5, 6, 6, 10]
  targets: ["163", "164"]
  mode_type: 0
  master_seed: 233
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["8", 1.0]
  risk_overrides:
    - [2200, "153", 0.6]
    - [2200, "225", 1.0]
    - [2200, "224", 1.0]
    - [2200, "201", 0.6]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.3
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200


cruise_ship_case_2:
  environment: "cruise_ship"
  sources: ["20", "49", "73", "84", "154"]
  agents: [5, 5, 6, 6, 5]
  targets: ["163", "164"]
  mode_type: 0
  master_seed: 233
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["8", 1.0]
  risk_overrides:
    - [2200, "153", 0.6]
    - [2200, "225", 1.0]
    - [2200, "224", 1.0]
    - [2200, "201", 0.6]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.3
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200


cruise_ship_case_3:
  environment: "cruise_ship"
  sources: ["12", "61", "75", "43", "31"]
  agents: [5, 5, 6, 6, 5]
  targets: ["163", "164"]
  mode_type: 0
  master_seed: 233
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["8", 1.0]
  risk_overrides:
    - [2200, "153", 0.6]
    - [2200, "225", 1.0]
    - [2200, "224", 1.0]
    - [2200, "201", 0.6]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.3
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_4:
  environment: "cruise_ship"
  sources: ["6", "68", "78", "55", "43"]
  agents: [5, 5, 6, 6, 5]
  targets: ["163", "164"]
  mode_type: 0
  master_seed: 233
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["8", 1.0]
  risk_overrides:
    - [2200, "153", 0.6]
    - [2200, "225", 1.0]
    - [2200, "224", 1.0]
    - [2200, "201", 0.6]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.3
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_5:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 1006
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
  risk_overrides: []
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_6:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 1005
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["40", 1.0]
    - ["41", 1.0]
    - ["42", 1.0]
    - ["43", 1.0]
  risk_overrides:
    - [2400, "201", 1.0]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_7:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 1007
  risk_iterations: 7500
  risk_increase_chance: 0.05
  starting_risks:
    - ["6", 1.0]
    - ["70", 1.0]
    - ["71", 1.0]
    - ["72", 1.0]
    - ["173", 1.0]
    - ["144", 1.0]
  risk_overrides: []
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_8:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 1008
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["6", 1.0]
    - ["7", 1.0]
  risk_overrides:
    - [3000, "172", 0.8]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_9:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 1009
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - ["14", 1.0]
    - ["30", 1.0]
    - ["31", 1.0]
    - ["75", 1.0]
  risk_overrides: []
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

cruise_ship_case_10:
  environment: "cruise_ship"
  sources: ["82", "83"]
  agents: [5, 5]
  targets: ["163", "164"]
  mode_type: 1
  master_seed: 1010
  risk_iterations: 7500
  risk_increase_chance: 0.05
  starting_risks:
    - ["11", 1.0]
    - ["10", 1.0]
    - ["60", 1.0]
    - ["55", 1.0]
    - ["139", 1.0]
  risk_overrides:
    - [3000, "165", 1.0]
    - [3000, "103", 1.0]
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

####################################

######## THEME PARK CASES ########

theme_park_case_1:
  environment: "theme_park"
  sources: [ "69", "51", "18", "30" ]
  agents: [ 13, 7, 6, 4 ]
  targets: [ "65", "23" ]
  mode_type: 0
  master_seed: 2468
  risk_iterations: 7000
  risk_increase_chance: 0.01
  starting_risks:
    - [ "67", 1.0 ]
    - [ "54", 1.0 ]
    - [ "28", 1.0 ]
    - [ "17", 1.0 ]
    - [ "11", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_2:
  environment: "theme_park"
  sources: [ "5", "57", "37", "14" ]
  agents: [ 13, 6, 5, 4 ]
  targets: [ "65", "23" ]
  mode_type: 0
  master_seed: 2468
  risk_iterations: 7000
  risk_increase_chance: 0.01
  starting_risks:
    - [ "67", 1.0 ]
    - [ "54", 1.0 ]
    - [ "28", 1.0 ]
    - [ "17", 1.0 ]
    - [ "11", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_3:
  environment: "theme_park"
  sources: [ "43", "45", "1", "48" ]
  agents: [ 4, 7, 6, 4 ]
  targets: [ "65", "23" ]
  mode_type: 0
  master_seed: 2468
  risk_iterations: 7000
  risk_increase_chance: 0.01
  starting_risks:
    - [ "67", 1.0 ]
    - [ "54", 1.0 ]
    - [ "28", 1.0 ]
    - [ "17", 1.0 ]
    - [ "11", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_4:
  environment: "theme_park"
  sources: [ "49", "58", "7", "33" ]
  agents: [ 13, 7, 6, 4 ]
  targets: [ "65", "23" ]
  mode_type: 0
  master_seed: 2468
  risk_iterations: 7000
  risk_increase_chance: 0.01
  starting_risks:
    - [ "67", 1.0 ]
    - [ "54", 1.0 ]
    - [ "28", 1.0 ]
    - [ "17", 1.0 ]
    - [ "11", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_5:
  environment: "theme_park"
  sources: [ "49", "58", "7", "33" ]
  agents: [ 13, 7, 6, 4 ]
  targets: [ "65", "23" ]
  mode_type: 0
  master_seed: 2468
  risk_iterations: 7000
  risk_increase_chance: 0.01
  starting_risks:
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_6:
  environment: "theme_park"
  sources: [ "69", "14"]
  agents: [ 13, 7]
  targets: [ "50"]
  mode_type: 0
  master_seed: 2465
  risk_iterations: 7000
  risk_increase_chance: 0.02
  starting_risks:
    - [ "41", 0.5 ]
    - [ "48", 0.5 ]
    - [ "46", 0.5 ]
    - [ "3", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.5
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_7:
  environment: "theme_park"
  sources: [ "65", "14" ]
  agents: [ 13, 7 ]
  targets: [ "35" ]
  mode_type: 0
  master_seed: 246
  risk_iterations: 7000
  risk_increase_chance: 0.02
  starting_risks:
    - [ "48", 0.5 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_8:
  environment: "theme_park"
  sources: [ "5", "14" ]
  agents: [ 5, 7 ]
  targets: [ "65" ]
  mode_type: 0
  master_seed: 246
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
    - [ "69", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_9:
  environment: "theme_park"
  sources: [ "5", "14" ]
  agents: [ 5, 7 ]
  targets: [ "65" ]
  mode_type: 0
  master_seed: 2469
  risk_iterations: 7000
  risk_increase_chance: 0.02
  starting_risks:
    - [ "67", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

theme_park_case_10:
  environment: "theme_park"
  sources: [ "3", "14" , "69", "19"]
  agents: [ 5, 7, 6, 5]
  targets: [ "50" ]
  mode_type: 0
  master_seed: 2469
  risk_iterations: 7000
  risk_increase_chance: 0.02
  starting_risks:
    - [ "67", 1.0 ]
  risk_overrides:
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200

####################################

####### only in experiments.ipyb ############
crowding:
  environment: "cruise_ship_v2"
  sources: ["82", "83", "110", "92", "58", "45", "80", "103", "119", "25", "64", "32", "136", "141", "170", "148", "6", "172", "209", "208"]
  agents: [3, 3, 8, 30, 5, 3, 4, 2, 5, 4, 3, 2, 3, 1, 2, 3, 2, 3, 1, 3]
  targets: ["163", "164", "226", "227"]
  mode_type: 4
  master_seed: 1234
  risk_iterations: 7000
  risk_increase_chance: 0.05
  starting_risks:
  risk_overrides: null
  risk_threshold: 0.5
  propagation_threshold: 0.5
  gamma: 0.2
  stairs_max_speed: 0.6
  normal_max_speed: 1.2
  every_nth_frame_simulation: 3
  every_nth_frame_animation: 50
  danger_visualization_frame: 1200